### ISSUE TITLE
[Security] Usage example is vulnerable

### ISSUE THREAD

**Issue by tr4l** [peter-murray/issue-forms-body-parser#5]
The usage example is sensible to script injection

How to reproduce:
>>demo-repository-owner<<
octodemo

>>demo-repository-name<<
pm-automation-test-001

>>template<<
octodemo/template-demo-github-user-search";ls /;echo "

**Comment by peter-murray** [comment]
This was resolved with best practice examples for avoiding injection attacks when showing the data. It is expected that users would treat this as untrusted data but the examples definitely needed updating. Thank you for reporting 🙇

**Comment by tr4l** [comment]
The use of echo '${{ env.parsed_data }}' is still vulnerable, as $ {{ }} is doing string replacement before the execution.

You can check how to fix on https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections

Or the mitigations chapter on https://cycode.com/blog/github-actions-vulnerabilities/

Basically, once you declared env, as you have already done, you use them as env variable ( $ XXX ) instead of string replacement ${{XXX}}
